### PR TITLE
Include QCloseEvent in IEditor.cpp

### PR DESCRIPTION
**Pull request by EthanArmbrust**
Without this include, project fails to build on Arch Linux with gcc 9.3.0 with the following error:
```
../src/Editor/IEditor.cpp:79:15: error: invalid use of incomplete type ‘class QCloseEvent’
   79 |         pEvent->ignore();
      |               ^~
```

### CODE REVIEW

**Comment by jackoalan** [comment]
Thank you! I've had to add that to some other programs recently too
